### ISSUE TITLE
[feature] Show if and where a domain redirects to another domain

### ISSUE THREAD

**Issue by RuboGubo** [Bytezz/IPLookup-gtk#6]
If the domain has a re-direct to another domain, then it should tell you and offer to analyse that domain.

An example website would be ft.co.uk → ft.com

**Comment by Bytezz** [comment]
ft.co.uk and ft.com are actually two different IPs (151.101.0.204 and 151.101.194.209)
The redirection will probably occur in http within the web browser (through html or js).

What do you think about showing the IP of a given domain name?

**Comment by RuboGubo** [comment]
Yeah, that would prob also work quite well

**Comment by Bytezz** [comment]
Would this be ok?

[Changing IP field content](https://github.com/Bytezz/IPLookup-gtk/assets/25850701/0b17eaa6-0a96-452b-b162-ee66c5ebe45e)

**Comment by RuboGubo** [comment]
idk? might be better to have a separate field for it in the list of info bellow, works for now though.

**Comment by Bytezz** [comment]
Here it is. Now if user input a domain name, a new field appear showing its IP.

I think http redirection check would be out of scope, since this tool is for getting just IP info.

If you are satisfied with this edit (see video below), I can close this feature request.
If someone else would open a feature request like this in the future then I will evaluate whether it should be implemented.

[IP row](https://github.com/Bytezz/IPLookup-gtk/assets/25850701/b53c4dfc-ed15-4d0a-83a7-c370ce548b43)

**Comment by RuboGubo** [comment]
Yeah, that seems amazing, thanks!
